faculty/urls.py
from django.conf.urls import patterns, include, url
from faculty import views
from django.contrib.auth.decorators import login_required
#from django.views.generic import ListView


urlpatterns = patterns('',
	url(r'^$', views.FacultyView, name='bulletin'),
	#url(r'^bulletin/(?P<pk>\d+)/$', views.BulletinView.as_view(), name='bulletin'),
	url(r'^profile/$', views.ProfileView, name='profile'),
	url(r'^profile/edit/(?P<id>\d+)/$', login_required(views.EditFacultyView.as_view()), name='edit-profile'),
	url(r'^shelf/$', views.ShelfView, name='shelf'),
	url(r'^program/$', login_required(views.ProgramView.as_view()), name='program'),
	url(r'^program/(?P<pk>\d+)/$', login_required(views.ProgramDetailView.as_view()), name='programdetail'),
	url(r'^news/$', login_required(views.NewsView.as_view()), name='news'),
	url(r'^notification/$', login_required(views.NotificationView.as_view()), name='notification'),
	url(r'^contact/$', login_required(views.ContactView.as_view()), name='contact'),
	url(r'^faculty_info/$', login_required(views.FacultyInfoView.as_view()), name='facultyinfo'),
	# url(r'^chatroom/$', views.ChatroomView, name='chatroom'),
	# url(r'^chat/', include('chatrooms.urls', namespace='chatroom')),
	
)

general/urls.py
from django.conf.urls import patterns, include, url
from general import views
from django.views.generic import ListView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
	url(r'^$', views.HomeView.as_view(), name='home'),
	url(r'^program/$', views.ProgramView.as_view(), name='program'),
	url(r'^program/(?P<pk>\d+)/$', views.ProgramDetailView.as_view(), name='programdetail'),
	url(r'^news/$', views.NewsView.as_view(), name='news'),
	url(r'^notification/$', views.NotificationView.as_view(), name='notification'),
	url(r'^contact/$', views.ContactView.as_view(), name='contact'),
	url(r'^faculty_info/$', views.FacultyInfoView.as_view(), name='facultyinfo'),
	# url(r'^accounts/register/$', views.accountRegisterView, name='accountregister'),
    # url(r'^accounts/register_success/$', views.accountRegisterSuccessView, name='accountregistersuccess'),
    url(r'^accounts/login/$', views.accountLoginView, name='accountlogin'),
    url(r'^accounts/logout/$', views.accountLogoutView, name='accountlogout'),
    url(r'^accounts/auth/$', views.accountAuthView, name='accountauth'),
    url(r'^accounts/invalid/$', views.accountInvalidView, name='accountinvalid'),
	url(r'^accounts/$', login_required(views.Account_HomeView.as_view()), name='accounthome'),
    url(r'^accounts/program/$', login_required(views.AccountProgramView.as_view()), name='accountprogram'),
	url(r'^accounts/program/(?P<pk>\d+)/$', login_required(views.AccountProgramDetailView.as_view()), name='accountprogramdetail'),
	url(r'^accounts/news/$', login_required(views.AccountNewsView.as_view()), name='news'),
	url(r'^accounts/notification/$', login_required(views.AccountNotificationView.as_view()), name='accountnotification'),
	url(r'^accounts/contact/$', login_required(views.AccountContactView.as_view()), name='accountcontact'),
	url(r'^accounts/faculty_info/$', login_required(views.AccountFacultyInfoView.as_view()), name='accountfacultyinfo'),

)

urlpatterns += staticfiles_urlpatterns()

ims_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#for loading static files:
from django.conf.urls.static import static
from django.conf import settings

# from django.db.models.loading import cache as model_cache

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# if not model_cache.loaded:
#     model_cache.get_models()
   
admin.autodiscover()


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^faculty/', include('faculty.urls',namespace = "faculty")),
    url(r'^students/', include('students.urls',namespace = "students")),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('general.urls',namespace = "general")),
    # url(r'^tribune/', include('djangotribune.urls')),
    url(r'^chat/', include('jqchat.urls')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

jqchat/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url, include

import views

urlpatterns = patterns('',
    # Example chat room.
    url(r"room/(?P<id>\d+)/$", views.window, name="jqchat_test_window"),
    url(r"room/(?P<id>\d+)/ajax/$", views.BasicAjaxHandler, name="jqchat_ajax"),
    # Second example room - adds room descriptions.
    url(r"room_with_description/(?P<id>\d+)/$", views.WindowWithDescription, name="jqchat_test_window_with_description"),
    url(r"room_with_description/(?P<id>\d+)/ajax/$", views.WindowWithDescriptionAjaxHandler, name="jqchat_test_window_with_description_ajax"),
)

faculty/models.py
from django.db import models
# from students.models import  Batch
from django.contrib.auth.models import User
# from students.models import Time_Slot
from django.core.urlresolvers import reverse
# from registration.models import RegistrationProfile

# Create your models here.
#Table structure for table `Faculty_Info`


class Faculty_Time_Table(models.Model):
    DAY_CHOICES = (
        (u'1', u'Monday'),
        (u'2', u'Tuesday'),
        (u'3', u'Wednessday'),
        (u'4', u'Thursday'),
        (u'5', u'Friday'),
        (u'6', u'Saturday'),
    )
    Faculty = models.ForeignKey('general.Faculty')
    Day = models.CharField(max_length=1, choices=DAY_CHOICES)
    Time_Slot = models.ForeignKey('students.Time_Slot')
    Subject = models.CharField(max_length=20)
    Subject_Id = models.CharField(max_length=10)
    Batch = models.ForeignKey('students.Batch')

    def __unicode__(self):  # Python 3: def __str__(self):
        return str(self.Batch)

students/models.py
from django.db import models
# from apps.faculty.models import Faculty
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from general.models import Course
from django.forms import ModelForm
from django.core.urlresolvers import reverse
# from registration.models import RegistrationProfile
import registration

# Create your models here.
class Slot(models.Model):
    SLOT_CHOICES = (
        (u'1', u'First'),
        (u'2', u'Second'),
        )
    Slot = models.CharField(max_length=1, choices=SLOT_CHOICES)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Slot

class Batch(models.Model):
    Course=models.ForeignKey(Course)
    Semester=models.CharField(max_length=15)
    Faculty =  models.ManyToManyField('general.Faculty', verbose_name=_('faculties'), blank=True
    )
    Room_Number = models.CharField(max_length=5)
    Slot =models.ForeignKey(Slot)

    def __unicode__(self):  # Python 3: def __str__(self)
        return str(self.Course.name + ' ' + self.Semester)
        

    


class Time_Slot(models.Model):
    
    Start_Time = models.TimeField()
    End_Time = models.TimeField()
    Slot = models.ForeignKey(Slot)

    def __unicode__(self):  # Python 3: def __str__(self):
        return str(self.Start_Time) + ' - ' + str(self.End_Time)


    

class Time_Table(models.Model):
    DAY_CHOICES = (
        (u'1', u'Monday'),
        (u'2', u'Tuesday'),
        (u'3', u'Wednessday'),
        (u'4', u'Thursday'),
        (u'5', u'Friday'),
        (u'6', u'Saturday'),
    )
    Day = models.CharField(max_length=1, choices=DAY_CHOICES)
    Time_Slot = models.ForeignKey(Time_Slot)
    Subject = models.CharField(max_length=20)
    Subject_Id = models.CharField(max_length=10)
    Faculty = models.ForeignKey('general.Faculty')
    Batch = models.ForeignKey(Batch)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Subject

   
class Notification(models.Model):
    Title = models.CharField(max_length=100)
    Link = models.URLField()
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Book(models.Model):
    Batch = models.ForeignKey(Batch)
    Title = models.CharField(max_length=100)
    Docfile = models.FileField(upload_to='documents/books/')
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Title

# class BookForm(ModelForm):
#     class Meta:
#         model = Book
#         exclude = ['Batch']
#         #fields = '__all__'
#         error_messages = {
#             NON_FIELD_ERRORS: {
#                 'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
#             }
#         }
        
#     # def get_absolute_url(self):
#     #     return reverse('events:team-detail', kwargs={'pk': self.pk})

class Question_Paper(models.Model):
    Batch = models.ForeignKey(Batch)
    Title = models.CharField(max_length=100)
    Question_Paper = models.FileField(upload_to='documents/books/')
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Title

class Link(models.Model):
    Batch = models.ForeignKey(Batch)
    Title = models.CharField(max_length=100)
    URL = models.URLField()
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Title

faculty/views.py
from django.http import HttpResponse
from general.models import Program, Course, News, Notification, Contact
from students.models import *
from general.models import *
from registration.forms import FacultyForm
from django.contrib.auth.models import User
from django.views.generic.list import ListView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView

# from django.core.context_processors import csrf
# from django.template import RequestContext,loader
# from django.views import generic
# from django.utils import timezone
from django.shortcuts import render, render_to_response

# @login_required
class HomeView(ListView):
    model = Program
    template_name = 'general/account-index.html'

    def get_context_data(self, **kwargs):
        ctx = super(HomeView, self).get_context_data(**kwargs)
        ctx['program_list'] = Program.objects.all()
        ctx['course_list'] = Course.objects.all()
        ctx['news_list'] = News.objects.order_by('-pub_date')[:5]
        ctx['notification_list']= Notification.objects.order_by('-pub_date')[:5]

        
        return ctx

class ProgramView(ListView):
    model = Program
    template_name = 'general/account-program.html'

    def get_queryset(self):
        return Program.objects.all()


# @login_required
class ProgramDetailView(SingleObjectMixin, ListView):
    
    template_name = "general/account-programdetail.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Program.objects.all())
        return super(ProgramDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(ProgramDetailView, self).get_context_data(**kwargs)
        ctx['program_list'] = Program.objects.all()
        ctx['course_list'] = Course.objects.all()

        return ctx
    def get_queryset(self):
        return self.object.course_set.all()

# @login_required
class NewsView(ListView):
    model = News
    template_name = 'general/account-news.html'

    def get_context_data(self, **kwargs):
        ctx = super(NewsView, self).get_context_data(**kwargs)
        ctx['program_list'] = Program.objects.all()
        ctx['course_list'] = Course.objects.all()

        return ctx


    
# @login_required
class NotificationView(ListView):
    model = Notification
    template_name = 'general/account-notification.html'

    
    def get_context_data(self, **kwargs):
        ctx = super(NotificationView, self).get_context_data(**kwargs)
        ctx['program_list'] = Program.objects.all()
        ctx['course_list'] = Course.objects.all()

        return ctx

# @login_required
class ContactView(ListView):
    model = Contact
    template_name = 'general/account-contact.html' 

    def get_context_data(self, **kwargs):
        ctx = super(ContactView, self).get_context_data(**kwargs)
        ctx['program_list'] = Program.objects.all()
        ctx['course_list'] = Course.objects.all()

        return ctx 

# @login_required
class FacultyInfoView(ListView):
    context_object_name= 'item_list'
    template_name = 'faculty/account-facultyinfo.html'   

    def get_queryset(self):
        return Faculty.objects.all()

    def get_context_data(self, **kwargs):
        ctx = super(FacultyInfoView, self).get_context_data(**kwargs)
        ctx['program_list'] = Program.objects.all()
        ctx['course_list'] = Course.objects.all()

        return ctx  


# @login_required
def FacultyView(request):
    context= {}
    context['program_list'] = Program.objects.all()
    context['time_slot_list'] = Time_Slot.objects.all()
    context['notification_list'] = Notification.objects.all().order_by('-pub_date')[:5]
    context['user']=request.user
    # time table lists
    
    days = ['monday','tuesday','wednessday','thursday','friday','saturday']
    day_number = 0
    for day in days:
        context[day] = []
        day_number += 1
        time_table = request.user.faculty.faculty_time_table_set.filter(Day=day_number)
        for time in Time_Slot.objects.all():
            for item in time_table:
                if item.Time_Slot == time:
                    context[day].append(item)
                    break
            else:
                context[day].append('-')
    return render_to_response('faculty/bulletin.html', context)

    #context['profile']=request.user.profile #Profile.objects.get('User'=request__user)#request.user.profile
    

    



def ShelfView(request):
    context= {}
    context['program_list'] = Program.objects.all()
    context['user']=request.user
    context['profile']=request.user.faculty #Profile.objects.get('User'=request__user)#request.user.profile
    context['book_list'] = Book.objects.all()
    context['question_paper_list'] = Question_Paper.objects.all()
    context['link_list'] = Link.objects.all()
    
    return render_to_response('faculty/shelf.html', context)

def ProfileView(request):
    context= {}
    context['program_list'] = Program.objects.all()
    context['user']=request.user
    context['profile']=request.user.faculty #Profile.objects.get('User'=request__user)#request.user.profile
    
    return render_to_response('faculty/profile.html', context)

def ChatroomView(request):
    context= {}
    context['program_list'] = Program.objects.all()
    context['user']=request.user
    context['profile']=request.user.profile #Profile.objects.get('User'=request__user)#request.user.profile
    
    return render_to_response('faculty/classroom.html', context)

class EditFacultyView(UpdateView):
    model = Faculty
    form_class = FacultyForm
    template_name = 'faculty/edit-profile.html'

    def get(self, request, **kwargs):
        self.object = Faculty.objects.get(User = User.objects.get(id=self.kwargs['id']))
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

    def get_object(self, queryset=None):
        obj = Faculty.objects.get(User = User.objects.get(id=self.kwargs['id']))
        return obj

templates/faculty/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="INTERNATIONAL INSTITUTE OF PROFESSIONAL STUDIES">
    <meta name="author" content="">
    
    <title>{% block title %} COLLEGE|DYNAMIC {% endblock %}</title>
    

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'general/mb/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'general/mb/css/modern-business.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'general/mb/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extra_head %} {% endblock %}
</head>

<body>






<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'general:accounthome' %}">HOME</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    
                    
                    <li>
                        <a href="{% url 'general:accountprogramdetail' 1 %}">Programs</a>
                    </li>
                    <li>
                        <a href="{% url 'general:accountfacultyinfo' %}">Faculty Information</a>
                    </li>
                    <!-- <li>
                        <a href="{% url 'general:accountcontact' %}">Contact</a>
                    </li> -->
                    <li>
                        <a href="{% url 'faculty:bulletin' %}">Faculty's Corner</a>
                    </li>
                    <li>
                        <a href="{% url 'general:accountlogout' %}">Logout</a>
                    </li>
                   
                    
                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% block content %}{% endblock %}
    <!-- ######### footer #############-->
    <font color="white">....</font>
     <footer style="margin-top:10%" >
        <!-- Call to Action Section -->
      
        
       

        <!-- Footer -->
        
            <div class="row">
                <div class="col-lg-9">
                    <p>Copyright &copy; Website 2015</p>
                </div>
            
                <div class="col-lg-3" align="right ">
                    <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="#"><i class="fa fa-facebook-square"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-linkedin-square"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter-square"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-google-plus-square"></i></a>
                    </li>
                    </ul>
                    
                </div>
            </div>
           
            

        </footer>

   
    <!-- /.container -->

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'general/mb/js/bootstrap.min.js' %} "></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>


 <!-- jQuery -->
    
    <!-- Contact Form JavaScript -->
    <!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
    <script language="JavaScript" type="text/javascript" src="{% static 'general/mb/js/jquery.min.js' %}"></script>
    
    <script language="JavaScript" type="text/javascript" src="{% static 'general/mb/js/jquery.js' %}"></script>
    
    <script src="{% static 'general/mb/js/bootstrap.min.js' %} "></script>

    <script src="{% static 'general/mb/js/jqBootstrapValidation.js' %}"></script>
    
    
    <!-- // <script src="{% static 'jqchat/jqchat.js' %}"></script> -->

</body>
</html>

templates/faculty/bulletin.html
{% extends 'faculty/corner-base.html' %}
{% load staticfiles %}
{% block content1 %}
<!-- Block Content -->
<!--div class="row">
            
  hello {{user.username}} - {{user.first_name}}  {{user.last_name}} <br>
  D/O : {{user.profile.Father_Name}}    <br>
  Batch : {{user.profile.Batch.Slot}}
<ul>
         <li>Time-Table and Announcements</li>
			<li class=""> Email</li>
			<li class=""> Exam Schedule</li>
			<li> Result</li>
			
        </ul>


</div-->   
<div class="row">
<div class="col-md-8">
	<table class="table table-striped">
	    <thead>
	      <tr>
	      	<th></th>
	      	{% for time in time_slot_list %}
	        	<th>{{time}}</th>
	        {% endfor %}
	      </tr>
	    </thead>
	    <tbody>
	    	
	      <tr>
	        <th>Monday</th>
	        {% for item in monday %}
	        	<td>{{ item }} {{ item.Subject }}</td>	
	        {% endfor %}
	      </tr>
	      
	      <tr>
	        <th>Tuesday</th> 
	        {% for item in tuesday %}
	        	<td>{{ item }} {{ item.Subject }}</td>	
	        {% endfor %}
	        
	      </tr>
	      <tr>
	        <th>Wednesday</th>
	        {% for item in wednessday %}
	        	<td>{{ item }} {{ item.Subject }}</td>	
	        {% endfor %}
	      </tr>
	      <tr>
	        <th>Thursday</th> 
	        {% for item in thursday %}
	        	<td>{{ item }} {{ item.Subject }}</td>	
	        {% endfor %}
	      </tr>
	      <tr>
	        <th>Friday</th> 
	        {% for item in friday %}
	        	<td>{{ item }} {{ item.Subject }}</td>	
	        {% endfor %}
	      </tr>
	      <tr>
	        <th>Saturday</th>
	        
	        {% for item in saturday %}
				<td>{{ item }} {{ item.Subject }}</td>	
	        {% endfor %}
	      </tr>
	    
	    </tbody>
	</table>  
</div>

<div class="col-md-4">
	<div class="panel panel-default">
        <div class="panel-heading">
            <center><h4> Notice & Announcements</h4></center>
        </div>
        <div class="panel-body">
            
            {% if notification_list %}
            

                {% for notification in notification_list %}
                <span class='glyphicon glyphicon-pushpin' ></span>
                <a href="{{notification.Link}}" target="_blank">{{ notification.Title }} </a></br>
                {% endfor %}
            
            {% else %}
                <p>No Notification are available.</p>
            {% endif %}

        </div>
    </div>
</div>
</div>
{% endblock %}

templates/faculty/chat_test.html
{% extends "jqchat/base.html" %}
{% load staticfiles %}


{# An example chat window #}


<script type="text/javascript">
	$(document).ready(function(){
		console.log("init chat window!!");
		InitChatWindow("{% url jqchat_ajax room.id %}", null);
	});
</script>
{% block body %}
<div id="chat_left_col">
	<h1>Test Chat Client</h1>
	
	<p>This is a demo of the <a href="http://code.google.com/p/django-jqchat/">
	django-jqchat chat client</a>.</p>
	<p>This page shows the basic client. For an example of how to extend it,
	<a href="{% url jqchat_test_window_with_description room.id %}">see here</a>.</p>
	<p>There are 2 rooms in this demo,
	<a href="{% url jqchat_test_window 1 %}">here</a> and 
	<a href="{% url jqchat_test_window 2 %}">here</a>.</p>
</div>

<h2>Room name: {{ room }}</h2>

{% include 'jqchat/_chat_form.html' %}

<script type="text/javascript">document.getElementById("msg").focus();</script>
<script src="{% static 'general/mb/js/jquery.min.js' %}"></script>
<script src="{% static 'jqchat/jqchat.js' %}"></script>
{% endblock %}

templates/faculty/classroom.html
{% extends 'faculty/corner-base.html' %}
{% load staticfiles %}
{% block content1 %}
<!-- Block Content -->
{% endblock %}

templates/faculty/corner-base.html
{% extends "faculty/base.html" %}
{% load staticfiles %}

{% block content %}
<div id="content">
        <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"> Faculty's Corner
                    
                </h1>
                <ol class="breadcrumb">
                {% block breadcrumb %}
                    <li><a href="{% url 'general:home' %}">Home</a>
                    </li>
                    <li class="active">Student</li>
                {% endblock %}
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
            <div class="col-md-3">
                <div class="list-group">
                        <a href="{% url 'faculty:bulletin'%}" class="list-group-item">Bulletin-Board</a>
                        <a href="{% url 'faculty:shelf'%}" class="list-group-item">My Shelf</a>
                        <a href="/chat/rooms" class="list-group-item">Chatroom</a>
                        <a href="{% url 'faculty:profile'%}" class="list-group-item">Profile</a>
                </div>
            </div>
            <!-- Content Column -->
            <div class="col-md-9">
                <!-- Page Content -->
                {% block content1 %}{% endblock %}       
            </div>
`       </div>
        <!-- /.row -->
    </div>

<hr>
</div>
{% endblock %}

templates/faculty/faculty.html
{% extends "general/account-base.html" %}
{% block content %}

<h1>Faculty</h1>

{% endblock %}

templates/faculty/profile.html
{% extends 'faculty/corner-base.html' %}
{% load staticfiles %}
{% block content1 %}
<!-- Block Content -->
<h1>Profile</h1>
<hr>
<div class="row">
            <div class="col-md-4">
                
                    <img class="img-responsive " src="{{user.faculty.Picture}}" alt="">
                
            </div>
            <div class="col-md-8">
                <table class="table">
                	<tr>
                		<th>Name</th>
                		<td> {{user.faculty.Name }}</td>
                	</tr>
                	<tr>
                		<th>Qualification</th>
                		<td>{{ user.faculty.Qualification}}</td>
                	</tr>
                	<tr>
                		<th>Designation</th>
                		<td>{{ user.faculty.Mother_Name }}</td>
                	</tr>
                	<tr>
                		<th>Joining Date</th>
                		<td>{{ user.faculty.DOJ }}</td>
                	</tr>
                	<tr>
                		<th>Previous Job</th>
                		<td>{{ user.faculty.Permanent_Address }}</td>
                	</tr>
                	<!-- <tr>
                		<th>Roll Number</th>
                		<td>{{ user.faculty.Roll_Number }}</td>
                	</tr> -->
                	<tr>
                		<th>Area of innterest</th>
                		<td>{{ user.faculty.Area_Of_Interest }}</td>
                	</tr>
                </table>
            </div>
</div>
<a class="btn btn-primary" href="{% url 'faculty:edit-profile' user.id %}">Edit</i></a>

{% endblock %}

templates/faculty/profile1.html
{% extends 'faculty/corner-base.html' %}
{% load staticfiles %}
{% block content1 %}
<!-- Block Content -->
<h1>Profile</h1>
<hr>
<div class="row">
            <div class="col-md-4">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover" src="{{user.profile.Picture}}" alt="">
                </a>
            </div>
            <div class="col-md-8">
                <table class="table">
                	<tr>
                		<th>Name</th>
                		<td> {{user.first_name}}  {{user.last_name}}</td>
                	</tr>
                	<tr>
                		<th>Father's Name</th>
                		<td>{{ user.profile.Father_Name }}</td>
                	</tr>
                	<tr>
                		<th>Mother's Name</th>
                		<td>{{ user.profile.Mother_Name }}</td>
                	</tr>
                	<tr>
                		<th>DOB</th>
                		<td>{{ user.profile.DOB }}</td>
                	</tr>
                	<tr>
                		<th>Parmanent Address</th>
                		<td>{{ user.profile.Permanent_Address }}</td>
                	</tr>
                	<tr>
                		<th>Roll Number</th>
                		<td>{{ user.profile.Roll_Number }}</td>
                	</tr>
                	<tr>
                		<th>Enrollment Number</th>
                		<td>{{ user.profile.Enrollment_Number }}</td>
                	</tr>
                </table>
            </div>
</div>
<a class="btn btn-primary" href="{% url 'students:edit-profile' user.id %}">Edit</i></a>

{% endblock %}