general/urls.py
from django.conf.urls import patterns, include, url
from general import views
from django.views.generic import ListView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
	url(r'^$', views.HomeView.as_view(), name='home'),
	url(r'^program/$', views.ProgramView.as_view(), name='program'),
	url(r'^program/(?P<pk>\d+)/$', views.ProgramDetailView.as_view(), name='programdetail'),
	url(r'^news/$', views.NewsView.as_view(), name='news'),
	url(r'^notification/$', views.NotificationView.as_view(), name='notification'),
	url(r'^contact/$', views.ContactView.as_view(), name='contact'),
	url(r'^faculty_info/$', views.FacultyInfoView.as_view(), name='facultyinfo'),
	# url(r'^accounts/register/$', views.accountRegisterView, name='accountregister'),
    # url(r'^accounts/register_success/$', views.accountRegisterSuccessView, name='accountregistersuccess'),
    url(r'^accounts/login/$', views.accountLoginView, name='accountlogin'),
    url(r'^accounts/logout/$', views.accountLogoutView, name='accountlogout'),
    url(r'^accounts/auth/$', views.accountAuthView, name='accountauth'),
    url(r'^accounts/invalid/$', views.accountInvalidView, name='accountinvalid'),
	url(r'^accounts/$', login_required(views.Account_HomeView.as_view()), name='accounthome'),
    url(r'^accounts/program/$', login_required(views.AccountProgramView.as_view()), name='accountprogram'),
	url(r'^accounts/program/(?P<pk>\d+)/$', login_required(views.AccountProgramDetailView.as_view()), name='accountprogramdetail'),
	url(r'^accounts/news/$', login_required(views.AccountNewsView.as_view()), name='news'),
	url(r'^accounts/notification/$', login_required(views.AccountNotificationView.as_view()), name='accountnotification'),
	url(r'^accounts/contact/$', login_required(views.AccountContactView.as_view()), name='accountcontact'),
	url(r'^accounts/faculty_info/$', login_required(views.AccountFacultyInfoView.as_view()), name='accountfacultyinfo'),

)

urlpatterns += staticfiles_urlpatterns()

ims_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#for loading static files:
from django.conf.urls.static import static
from django.conf import settings

# from django.db.models.loading import cache as model_cache

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# if not model_cache.loaded:
#     model_cache.get_models()
   
admin.autodiscover()


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^faculty/', include('faculty.urls',namespace = "faculty")),
    url(r'^students/', include('students.urls',namespace = "students")),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('general.urls',namespace = "general")),
    # url(r'^tribune/', include('djangotribune.urls')),
    url(r'^chat/', include('jqchat.urls')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

jqchat/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url, include

import views

urlpatterns = patterns('',
    # Example chat room.
    url(r"room/(?P<id>\d+)/$", views.window, name="jqchat_test_window"),
    url(r"room/(?P<id>\d+)/ajax/$", views.BasicAjaxHandler, name="jqchat_ajax"),
    # Second example room - adds room descriptions.
    url(r"room_with_description/(?P<id>\d+)/$", views.WindowWithDescription, name="jqchat_test_window_with_description"),
    url(r"room_with_description/(?P<id>\d+)/ajax/$", views.WindowWithDescriptionAjaxHandler, name="jqchat_test_window_with_description_ajax"),
)

general/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from jqchat.models import Room
from django.utils.encoding import python_2_unicode_compatible
from registration.users import UserModel, UserModelString
from registration.models import RegistrationManager
from django.forms import ModelForm
from ims_site import settings
from django.template import RequestContext, TemplateDoesNotExist
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse

try:
    from django.utils.timezone import now as datetime_now
except ImportError:
    datetime_now = datetime.datetime.now
# import pdb

# Create your models here.

# class Profile(models.Model):
#     #add any common fields here (first_name, last_name and email come from User)

#     #perhaps add is_student or is_teacher properites here
#     @property
#     def is_student(self):
#         try:
#             self.student
#             return True
#         except Student.DoesNotExist:
#             return False

#     @property
#     def is_faculty(self):
#         try:
#             self.faculty
#             return True
#         except Faculty.DoesNotExist:
#             return False
class Program(models.Model):
	name=models.CharField(max_length=30)
	def __unicode__(self):  # Python 3: def __str__(self)
		return self.name
    

@python_2_unicode_compatible
class RegistrationProfile(models.Model):
    """
    A simple profile which stores an activation key for use during
    user account registration.

    Generally, you will not want to interact directly with instances
    of this model; the provided manager includes methods
    for creating and activating new accounts, as well as for cleaning
    out accounts which have never been activated.

    While it is possible to use this model as the value of the
    ``AUTH_PROFILE_MODULE`` setting, it's not recommended that you do
    so. This model's sole purpose is to store data temporarily during
    account registration and activation.

    """
    # user = models.OneToOneField(UserModelString(), verbose_name=_('user'), null = True)
    user = models.OneToOneField(User)
    activation_key = models.CharField(_('activation key'), max_length=40)
    activated = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    objects = RegistrationManager()

    class Meta:
        verbose_name = _('registration profile')
        verbose_name_plural = _('registration profiles')

    def __str__(self):
        return "Registration information for %s" % self.user


    @property
    def is_student(self):
        try:
            self.student
            return True
        except Student.DoesNotExist:
            return False

    @property
    def is_faculty(self):
        try:
            self.faculty
            return True
        except Faculty.DoesNotExist:
            return False

    def activation_key_expired(self):
        """
        Determine whether this ``RegistrationProfile``'s activation
        key has expired, returning a boolean -- ``True`` if the key
        has expired.

        Key expiration is determined by a two-step process:

        1. If the user has already activated, ``self.activated`` will
           be ``True``. Re-activating is not permitted, and so this
           method returns ``True`` in this case.

        2. Otherwise, the date the user signed up is incremented by
           the number of days specified in the setting
           ``ACCOUNT_ACTIVATION_DAYS`` (which should be the number of
           days after signup during which a user is allowed to
           activate their account); if the result is less than or
           equal to the current date, the key has expired and this
           method returns ``True``.

        """
        expiration_date = datetime.timedelta(
            days=settings.ACCOUNT_ACTIVATION_DAYS)
        return (self.activated or
                (self.user.date_joined + expiration_date <= datetime_now()))
    activation_key_expired.boolean = True

    def send_activation_email(self, site, request=None):
        """
        Send an activation email to the user associated with this
        ``RegistrationProfile``.

        The activation email will make use of two templates:

        ``registration/activation_email_subject.txt``
            This template will be used for the subject line of the
            email. Because it is used as the subject line of an email,
            this template's output **must** be only a single line of
            text; output longer than one line will be forcibly joined
            into only a single line.

        ``registration/activation_email.txt``
            This template will be used for the text body of the email.

        ``registration/activation_email.html``
            This template will be used for the html body of the email.

        These templates will each receive the following context
        variables:

        ``user``
            The new user account

        ``activation_key``
            The activation key for the new account.

        ``expiration_days``
            The number of days remaining during which the account may
            be activated.

        ``site``
            An object representing the site on which the user
            registered; depending on whether ``django.contrib.sites``
            is installed, this may be an instance of either
            ``django.contrib.sites.models.Site`` (if the sites
            application is installed) or
            ``django.contrib.sites.requests.RequestSite`` (if
            not). Consult the documentation for the Django sites
            framework for details regarding these objects' interfaces.

        ``request``
            Optional Django's ``HttpRequest`` object from view.
            If supplied will be passed to the template for better
            flexibility via ``RequestContext``.
        """
        ctx_dict = {}
        if request is not None:
            ctx_dict = RequestContext(request, ctx_dict)
        # update ctx_dict after RequestContext is created
        # because template context processors
        # can overwrite some of the values like user
        # if django.contrib.auth.context_processors.auth is used
        ctx_dict.update({
            'user': self.user,
            'activation_key': self.activation_key,
            'expiration_days': settings.ACCOUNT_ACTIVATION_DAYS,
            'site': site,
        })
        subject = (getattr(settings, 'REGISTRATION_EMAIL_SUBJECT_PREFIX', '') +
                   render_to_string(
                       'registration/activation_email_subject.txt', ctx_dict))
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        from_email = getattr(settings, 'REGISTRATION_DEFAULT_FROM_EMAIL',
                             settings.DEFAULT_FROM_EMAIL)
        message_txt = render_to_string('registration/activation_email.txt',
                                       ctx_dict)

        email_message = EmailMultiAlternatives (subject, message_txt,
                                               from_email, [self.user.email])

        if getattr(settings, 'REGISTRATION_EMAIL_HTML', True):
            try:
                message_html = render_to_string(
                    'registration/activation_email.html', ctx_dict)
            except TemplateDoesNotExist:
                pass
            else:
                email_message.attach_alternative(message_html, 'text/html')
        # pdb.set_trace()
        email_message.send()

class Faculty(RegistrationProfile):
	Name=models.CharField(max_length=50)
	#Discipline =models.CharField(max_length=200)
	Designation=models.CharField(max_length=200)
	Responsibility=models.CharField(max_length=200)
	DOJ=models.DateField() 		#Date of Joining
	Qualification=models.CharField(max_length=200)
	Area_Of_Interest=models.CharField(max_length=200)
	Previous_Job=models.CharField(max_length=200)
	Web_Link=models.CharField(max_length=40,default=None)
	Blog_Link=models.CharField(max_length=40,default=None)
	Alternate_Email=models.CharField(max_length=40,default=None)
	Linkedin_Link=models.CharField(max_length=40,default=None)
	Facebook_Link=models.CharField(max_length=40,default=None)
	Googleplus_Link=models.CharField(max_length=40,default=None)
	Twitter_Link=models.CharField(max_length=40,default=None)
	Picture=models.URLField(max_length=100,default=None)
	Resume =models.URLField(max_length=40,default=None)#Link to resume
	def __unicode__(self):  # Python 3: def __str__(self):
		return self.Name

	def get_absolute_url(self):
		return reverse('faculty:profile')

	objects = RegistrationManager()



class Student(RegistrationProfile):
    Batch = models.ForeignKey('students.Batch')
    Father_Name =models.CharField(max_length=200)
    Mother_Name =models.CharField(max_length=200)
    DOB= models.DateField(max_length=200)
    Local_Address =models.CharField(max_length=200,default=None,blank=True)
    Permanent_Address =models.CharField(max_length=200,default = None)
    Mobile_Number =models.CharField(max_length=15,blank=True)
    Telephone_Number =models.CharField(max_length=200,default=None,blank=True)
    Roll_Number =models.CharField(max_length=200,default = None)
    Enrollment_Number =models.CharField(max_length=200,default=None)
    Picture=models.URLField(default=None,blank=True)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('students:profile')

    objects = RegistrationManager()



class Course(models.Model):

	DISCIPLINE_CHOICES = (
        ('TECHNICAL', 'Technical'),
        ('MANAGEMENT', 'Management'),
    )
    
	
	name = models.CharField(max_length=200)

students/models.py
from django.db import models
# from apps.faculty.models import Faculty
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from general.models import Course
from django.forms import ModelForm
from django.core.urlresolvers import reverse
# from registration.models import RegistrationProfile
import registration

# Create your models here.
class Slot(models.Model):
    SLOT_CHOICES = (
        (u'1', u'First'),
        (u'2', u'Second'),
        )
    Slot = models.CharField(max_length=1, choices=SLOT_CHOICES)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Slot

class Batch(models.Model):
    Course=models.ForeignKey(Course)
    Semester=models.CharField(max_length=15)
    Faculty =  models.ManyToManyField('general.Faculty', verbose_name=_('faculties'), blank=True
    )
    Room_Number = models.CharField(max_length=5)
    Slot =models.ForeignKey(Slot)

    def __unicode__(self):  # Python 3: def __str__(self)
        return str(self.Course.name + ' ' + self.Semester)
        

    


class Time_Slot(models.Model):
    
    Start_Time = models.TimeField()
    End_Time = models.TimeField()
    Slot = models.ForeignKey(Slot)

    def __unicode__(self):  # Python 3: def __str__(self):
        return str(self.Start_Time) + ' - ' + str(self.End_Time)


    

class Time_Table(models.Model):
    DAY_CHOICES = (
        (u'1', u'Monday'),
        (u'2', u'Tuesday'),
        (u'3', u'Wednessday'),
        (u'4', u'Thursday'),
        (u'5', u'Friday'),
        (u'6', u'Saturday'),
    )
    Day = models.CharField(max_length=1, choices=DAY_CHOICES)
    Time_Slot = models.ForeignKey(Time_Slot)
    Subject = models.CharField(max_length=20)
    Subject_Id = models.CharField(max_length=10)
    Faculty = models.ForeignKey('general.Faculty')
    Batch = models.ForeignKey(Batch)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Subject

   
class Notification(models.Model):
    Title = models.CharField(max_length=100)
    Link = models.URLField()
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Book(models.Model):
    Batch = models.ForeignKey(Batch)
    Title = models.CharField(max_length=100)
    Docfile = models.FileField(upload_to='documents/books/')
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Title

# class BookForm(ModelForm):
#     class Meta:
#         model = Book
#         exclude = ['Batch']
#         #fields = '__all__'
#         error_messages = {
#             NON_FIELD_ERRORS: {
#                 'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
#             }
#         }
        
#     # def get_absolute_url(self):
#     #     return reverse('events:team-detail', kwargs={'pk': self.pk})

class Question_Paper(models.Model):
    Batch = models.ForeignKey(Batch)
    Title = models.CharField(max_length=100)
    Question_Paper = models.FileField(upload_to='documents/books/')
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Title

class Link(models.Model):
    Batch = models.ForeignKey(Batch)
    Title = models.CharField(max_length=100)
    URL = models.URLField()
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.Title

templates/general/account-base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="INTERNATIONAL INSTITUTE OF PROFESSIONAL STUDIES">
    <meta name="author" content="">
    
    <title>{% block title %} COLLEGE|DYNAMIC {% endblock %}</title>
    

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'general/mb/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'general/mb/css/modern-business.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'general/mb/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extra_head %} {% endblock %}
</head>

<body>






<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'general:accounthome' %}">HOME</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    
                    
                    <li>
                        <a href="{% url 'general:accountprogramdetail' 1 %}">Programs</a>
                    </li>
                    <li>
                        <a href="{% url 'general:accountfacultyinfo' %}">Faculty Information</a>
                    </li>
                    <!-- <li>
                        <a href="{% url 'general:accountcontact' %}">Contact</a>
                    </li> -->
                    <li>
                        <a href="{% url 'general:accountcontact' %}">Corner</a>
                    </li>
                    <li>
                        <a href="{% url 'general:accountlogout' %}">Logout</a>
                    </li>
                   
                    
                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <!-- ######### footer #############-->
    <font color="white">....</font>
     <footer style="margin-top:10%" >
        <!-- Call to Action Section -->
      
        
       

        <!-- Footer -->
        
            <div class="row">
                <div class="col-lg-9">
                    <p>Copyright &copy; Website 2015</p>
                </div>
            
                <div class="col-lg-3" align="right ">
                    <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="#"><i class="fa fa-facebook-square"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-linkedin-square"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter-square"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-google-plus-square"></i></a>
                    </li>
                    </ul>
                    
                </div>
            </div>
           
            

        </footer>

   
    <!-- /.container -->

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'general/mb/js/bootstrap.min.js' %} "></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>


 <!-- jQuery -->
    
    <!-- Contact Form JavaScript -->
    <!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
    <script language="JavaScript" type="text/javascript" src="{% static 'general/mb/js/jquery.min.js' %}"></script>
    
    <script language="JavaScript" type="text/javascript" src="{% static 'general/mb/js/jquery.js' %}"></script>
    
    <script src="{% static 'general/mb/js/bootstrap.min.js' %} "></script>

    <script src="{% static 'general/mb/js/jqBootstrapValidation.js' %}"></script>
    
    
    <!-- // <script src="{% static 'jqchat/jqchat.js' %}"></script> -->

</body>
</html>

templates/general/account-faculty.html
{% extends "general/account-base.html" %}
{% block content %}

<h1>Faculty</h1>

{% endblock %}

templates/general/account-facultyinfo.html
{% extends accountbase %}
{% block content %}
{% if item_list %}

		<div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Team</h2>
                 <ol class="breadcrumb">
                    <li><a href="{% url 'general:home' %}">Home</a>
                    </li>
                    <li class="active">Faculty</li>
                </ol>
            </div>
            {% for item in item_list %}

            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="{{ item.Picture }}" alt=""  width=50%>
                    <div class="caption">
                        <h3>{{ item.Name }}<br>
                            <small>{{ item.Responsiblity }}</small>
                        </h3>
                        <h5>{{ item.Designation }}<br></h5>
                        <h6>Area of Interest: {{ item.Area_Of_Interest }}</h6><br>
                        <a href="{{ item.Web_Link }}"> {{ item.Name }}</a><br>
                        <a href="{{ item.Blog_Link }}"> Blog </a>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="{{ item.Linkedin_Link }}"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="{{ item.Twitter_Link }}"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                            <li><a href="{{ item.Googleplus_Link }}"><i class="fa fa-2x fa-google-plus-square"></i>
</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            
{% endfor %}

 {% else %}
 no member
 {% endif %}
{% endblock %}

templates/general/account-news.html
{% extends accountbase %}
{% load staticfiles %}
{% block content %}
<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">News
                    
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'general:home' %}">Home</a>
                    </li>
                    <li class="active">News</li>
                </ol>
            </div>
        </div><hr>
<ul>
	{% for news in news_list %}
	<li>
		<a href="../../media/{{news.Docfile}}" target="_blank">{{ news.Title }} </a> {{ news.pub_date }}
	</li>
	{% endfor %}
</ul>
{% endblock %}

templates/general/account-notification.html
{% extends accountbase %}
{% load staticfiles %}
{% block content %}

<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Notifications
                    
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'general:home' %}">Home</a>
                    </li>
                    <li class="active">Notifications</li>
                </ol>
            </div>
        </div>
<hr>
<ul>
	{% for notification in notification_list %}
	<li class = 'glyphicon glyphicon-pushpin'>
		<a href="{{ notification.Link }}" target="_blank">{{ notification.Title }} </a> {{ notification.pub_date }}
	</li><br>
	{% endfor %}
</ul>
{% endblock %}

templates/general/account-program.html
{% extends accountbase %}


{% load staticfiles %}


{% block title %}COLLEGE|PROGRAMS{% endblock %}


{% load url from future %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% block content %}
<!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Programs 
                    <small>We Offer </small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'general:home' %}">Home</a>
                    </li>
                    <li class="active">Programs</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
            <div class="col-md-3">
                <div class="list-group">
                	{% for item in program_list%}

                    	<a href="{% url 'general:programdetail' item.id %}" class="list-group-item">{{ item.name }}</a>
                    {% endfor %}	
                </div>
            </div>
            <!-- Content Column -->
            <div class="col-md-9">
                
                {% block content1 %}{% endblock %}
            </div>
        </div>
        <!-- /.row -->
</div>

        <hr>
{% endblock %}
        

templates/general/account_login.html
{% extends "general/base.html" %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Login
            
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'general:home' %}">Home</a>
            </li>
            <li class="active">Login</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    	<div class="panel panel-default text-center">
    		<div class="panel-heading">
                <h3 class="panel-title">Login</h3>
            </div>
            <div class="panel-body">
							
				{% if err %}
				<p class="error">Sorry, thats not a valid username or passwword</p>
				{% endif %}

				<form action="/accounts/auth/" method="post" >

				
				{% csrf_token %}
				<!--label for="group">Group</label><br>
				<input type="text" name="group" value="" id="group"><br-->
				<label for="username">Username</label>
				<input type="text" name="username" value="" id="username"><br>
				<label for="password">Password</label>
				<input type="password" name="password" value="" id="password"><br>
				<input type="submit" value="Submit" />
				</form>
			
			<hr>
				<p>Forgot your password? <a href="/accounts/password/reset/">Reset it</a>.</p>
				<p>Not a member? <a href="/accounts/register/">Register</a>.</p>
				
			</div>
			
		</div>
	</div>
	<div class="col-md-4">
	</div>
</div>
{% endblock %}

templates/general/facultyinfo.html
{% extends 'general/base.html' %}
{% block content %}
{% if item_list %}

		<div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Team</h2>
                 <ol class="breadcrumb">
                    <li><a href="{% url 'general:home' %}">Home</a>
                    </li>
                    <li class="active">Faculty</li>
                </ol>
            </div>
            {% for item in item_list %}

            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="{{ item.Picture }}" alt=""  width=50%>
                    <div class="caption">
                        <h3>{{ item.Name }}<br>
                            <small>{{ item.Responsiblity }}</small>
                        </h3>
                        <h5>{{ item.Designation }}<br></h5>
                        <h6>Area of Interest: {{ item.Area_Of_Interest }}</h6><br>
                        <a href="{{ item.Web_Link }}"> {{ item.Name }}</a><br>
                        <a href="{{ item.Blog_Link }}"> Blog </a>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="{{ item.Linkedin_Link }}"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="{{ item.Twitter_Link }}"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                            <li><a href="{{ item.Googleplus_Link }}"><i class="fa fa-2x fa-google-plus-square"></i>
</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            
{% endfor %}

 {% else %}
 no member
 {% endif %}
{% endblock %}

templates/general/notification.html
{% extends 'general/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Notifications
                    
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'general:home' %}">Home</a>
                    </li>
                    <li class="active">Notifications</li>
                </ol>
            </div>
        </div>
<hr>
<ul>
	{% for notification in notification_list %}
	<li class = 'glyphicon glyphicon-pushpin'>
		<a href="{{ notification.Link }}" target="_blank">{{ notification.Title }} </a> {{ notification.pub_date }}
	</li><br>
	{% endfor %}
</ul>
{% endblock %}